# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69ecc9c1e26523d3e1dcf1617e30671885b7d4026ff4fbc95290e1c28419c2d62034f8e7378e11465ae7012b92e9282a0b735bc2fa8912186e6b270a967643d3

test:
  secret_key_base: b9776980a94080411654dc8a339e489cf13128b04564b476f3787ba30e8cbce30d4ed5287a2fd4ad7972702e56e2c75ec243e477f74bddb60ffe6949253dec27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
